### ISSUE TITLE
Discussion about the web hosting services

### ISSUE THREAD

**Issue by mincong-h** [infiniot/infiniot-web#4]
I'd like to discuss the web hosting services here.

- Do we need a web hosting service? Personally, I prefer localhost over a fixed server. In particular, I have no idea how to ensure the security.
- Host accessibility. If we want to use web hosting services, is our server PING32 (located in France) accessible from China? If not, what will be the solution?
- CDN problem. I deleted all the external web resources (Bootstrap, jQuery, HighchartJS, ...) from the project. These resources are now linked to specific CDN. Would it be a problem for Chinese users?

Any idea?

**Comment by Wenfeng-GAO** [comment]
In my opinion, keep `local` for now is ok since we don't have any data yet.

For **CDN problem**, I don't know exactly your meaning of **specific CDN**, I'll test and see the code later.(when I have some more time :) )

**Comment by mincong-h** [comment]
> In my opinion, keep local for now is ok since we don't have any data yet.

Perfect. 👍 

> For CDN problem, I don't know exactly your meaning of specific CDN ...

For example, Bootstrap uses **[MaxCDN][maxcdn]** to store their data and jQuery uses jQuery CDN. When people load our web pages, the JS and CSS resources are loaded directly via CDN as following:

```html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
```

It means that if a CDN is denied by GFW (The Great Firewall of China), JS and CSS resources cannot be loaded. For web user, the page loaded in web browser will be out of shape. But currently, you're the only user in China, so that's OK 😄 . For android user, it should have not impact.

> I'll test and see the code later.

No problem, take your time!

[maxcdn]: https://www.maxcdn.com
